name: Tests

on:
  pull_request:
  
  push:
    branches:
      - main

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.6

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2

        with:
          cache: npm
          check-latest: true
          node-version-file: .nvmrc

      - name: Install dependencies
        run: npm ci
      - name: Run eslint
        run: npm run lint 
