name: Tests

on:
  pull_request:
  
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.6

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2

        with:
          cache: npm
          check-latest: true
          node-version-file: .nvmrc

      - name: Install dependencies
        run: npm ci
      - name: Run linting and testing
        run: npm run test 
