name: Update
run-name: Update deps list
on:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  GITHUB_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: write
  pull-requests: write

jobs:
  Get-latest-dependent-data:
    name: Get latest dependent data
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.6

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2

        with:
          cache: npm
          check-latest: true
          node-version-file: .nvmrc

      - name: Install dependencies
        run: npm ci

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install github-dependents-info
        run: pip install -U github-dependents-info

      # Getting the data this way is pretty gunky, especially as github-dependents-info
      # has a github action. However the way we're using gdi isn't really how it's
      # intended to be used. We're using it to gather and analyse info where as
      # gdi was built as a documentation tool. This is especially true of the
      # github action which doesn't give us the option to output this data as
      # something like json which we can programmatically interogate.
      - name: Pipe our deps to a json file
        run: github-dependents-info --repo alphagov/govuk-frontend --json > ./data/raw-deps.json
      
      - name: Pipe port deps
        run: |
          github-dependents-info --repo LandRegistry/govuk-frontend-jinja --json > ./data/raw-deps-govuk-frontend-jinja.json
          github-dependents-info --repo LandRegistry/govuk-frontend-wtf --json > ./data/raw-deps-govuk-frontend-wtf.json
          github-dependents-info --repo LandRegistry/govuk-frontend-flask --json > ./data/raw-deps-govuk-frontend-flask.json
          github-dependents-info --repo x-govuk/govuk-form-builder --json > ./data/raw-deps-govuk-form-builder.json
          github-dependents-info --repo x-govuk/govuk-components --json > ./data/raw-deps-govuk-components.json
          github-dependents-info --repo govuk-react/govuk-react --json > ./data/raw-deps-govuk-react.json

      - name: Update service owners
        run: npm run update-service-owners
      
      - name: Clean data files
        run: |
          rm -f ./data/filtered-data.json

      - name: Build filtered data
        run: npm run build-filtered-data
      
      - name: Generate key data
        run: npm run generate-key-data
      
      - name: Create pull request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update-filtered-data-${{ github.ref_name }}
          delete-branch: true
          commit-message: "Get latest filtered dependents data and rejections - ${{ github.ref_name }}"
          title: "Get latest filtered dependents data and rejections - ${{ github.ref_name }}"
          body: "Generated automatically by github action"
          base: ${{ github.head_ref }}
